package com.fouriApps.model.SUB_VO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 09:06:02 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxstg_Business_unitRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public xxstg_Business_unitRowImpl() {
    }

    /**
     * Gets xxstg_businessunits entity object.
     * @return the xxstg_businessunits
     */
    public EntityImpl getxxstg_businessunits() {
        return (EntityImpl)getEntity(0);
    }
}
