package com.fouriApps.model.SUB_VO;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 09:06:22 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxstg_Business_unitDefImpl extends ViewDefImpl {
    public xxstg_Business_unitDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public xxstg_Business_unitDefImpl() {
    }
}
