package com.fouriApps.model.SUB_VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 17 09:06:02 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxstg_Business_unitImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public xxstg_Business_unitImpl() {
    }
}
